### PR TITLE
Change dependency to fog-aws instead of fog

### PR DESCRIPTION
**Pull request by tmaier**
Get rid of unnecessary dependencies

untested™

### CODE REVIEW

**Comment by andrusha** [comment]
Looks like it breaks this `require` clause https://github.com/andrusha/middleman-cloudfront/blob/master/lib/middleman-cloudfront/commands.rb#L3

**Comment by rosskevin** [comment]
Please close this one, #23 does this and updates dependencies.

**Comment by tmaier** [comment]
Hi @rosskevin,

I really appreciate your work on #23. Getting to a version which supports middleman 4 is great.
When I created my pull requests I was not aware that your pull requests also includes other changes, next to the upgrade to middleman 4.

However, I am also in favor of having small pull request which do one thing, so that their changes are better foreseeable.

Besides this, #23 will also lead to a major release, as the support for middleman 3 will be dropped. I don't see how this particular change is related to middleman 4 and why it should not be possible to get this improvement into a new minor release which is still compatible to middleman 3.

Best,

Tobias

**Comment by tmaier** [comment]
@andrusha, I updated the branch with the mentioned change

**Comment by andrusha** [comment]
@tmaier fair enough, have you tried it manually on some sample site?

**Pull request closed without merging**
